export const en = {
  common: {
    loading: 'Loading',
    connectionError: 'Connection error',
  },
  home: {
    header: 'What to Eat ?',
    message: 'Welcome',
    variant: 'App variant: ',
    search: 'What to Eat ?',
    popularIngredientsTitle: "Popular Ingredients",
    infoText: "Please enter available ingredients.",
    warningText: "Please select from the list",
    existingIngredient: "This ingredient already exists",
    placeholder: "Ex: Tomato, Onion, Garlic, etc.",
    myIngredients: "My Ingredients",
  },
  suggestions: {
    header: 'Suggestions',
  },
  recipes: {},
  calculator: {},
  login: {
    username: 'Username',
    usernameHint: 'Enter your username',
    button: 'Login',
    password: 'Password',
    passwordHint: 'Enter your password',
    invalidCredentials: 'Invalid credentials',
  },
  profile: {
    header: 'Profile',
    logout: 'Logout',
    message: 'This screen has the iOS native large header.',
  },
  popularIngredients: {
    pepper: 'Pepper',
    salt: 'Salt',
    onion: 'Onion',
    garlic: 'Garlic',
    tomato: 'Tomato',
    potato: 'Potato',
    meat: 'Meat',
    chicken: 'Chicken',
    beef: 'Beef',
    pork: 'Pork',
    fish: 'Fish',
    egg: 'Egg',
    milk: 'Milk',
    cheese: 'Cheese',
    BlackPepper:'dsad',
    parsley:'parsley',
    mint:'Mint',
    Oregaron:'Oregaron',
    Cucumber:'Cucumber',
    chicken:'Chichken',
    redonion:'Red onion',
     oliveoil:'Olive oil',
    oil:'Oil',
    greenlentil:'Green lentil',
    flour:'Flour', 
    tomatopaste:'Tomoto paste', 
    pepperpaste:'Pepper paste',
    eggplant:'Egg plant',
    milk:' Milk',
    butter:'Butter',
    mushroom:'Mushroom',
    cheddarCheese:'Cheddar cheese',
    Anchovy:'Anchovy',
    chickenbreast:'Chicken breast',
    cornflour:'Corn flour',
    Yoghurt:'Yoghurt',
    Bread:'Bread',
    Cumin: 'Cumin',
    chiliPepper:'Chili pepper',
    lemon:'Lemon',
    Spinach:'Spinach', 
   dryYeast: 'dry yeast',
    dough:'dough',
    Courgette:'Courgette',
    cream:'Cream',
   rice: 'Rice',
    walnut:'Walnut',
    Powdered:'powdered sugar',
    sugar:'Sugar',
    bakingPowder:'Baking powder',
    beans:'Beans',
    tarhana:'Tarhana',
    MeatWater:'Meat water'
    
  }
};
