export const tr = {
  common: {
    loading: 'Yükleniyor',
    connectionError: 'Bağlantı hatası',
  },
  home: {
    header: 'Ne Yemeli ?',
    message: 'Hoşgeldiniz',
    variant: 'Uygulama sürümü: ',
    search: 'Ne Yemeli ?',
    popularIngredientsTitle: "Popüler Malzemeler",
    infoText: "Lütfen mevcut malzemelerinizi giriniz.",
    warningText: "Lütfen listeden seçiniz",
    existingIngredient: "Bu malzeme zaten mevcut",
    placeholder: "Örnek: Domates, Soğan, Sarımsak, vb.",
    myIngredients: "Malzemelerim",
  },
  recipes: {},
  calculator: {},
  login: {
    username: 'Kullanıcı Adı',
    usernameHint: 'Kullanıcı adınızı giriniz',
    button: 'Giriş',
    password: 'Şifre',
    passwordHint: 'Şifrenizi giriniz',
    invalidCredentials: 'Geçersiz kimlik bilgileri',
  },
  profile: {
    header: 'Profil',
    logout: 'Çıkış',
    message: 'Bu ekran iOS native büyük başlık özelliğine sahiptir.',
  },
  popularIngredients: {
    pepper: 'Karabiber',
    salt: 'Tuz',
    onion: 'Soğan',
    garlic: 'Sarımsak',
    tomato: 'Domates',
    potato: 'Patates',
    meat: 'Et',
    chicken: 'Tavuk',
    beef: 'Kırmızı Et',
    pork: 'Domuz Et',
    fish: 'Balık',
    egg: 'Yumurta',
    milk: 'Süt',
    cheese: 'Peynir',
  }
};
